### PR TITLE
Modal should keep focus on escape key if @keyboard=false and on backdrop click @backdropClose=false

### PR DESCRIPTION
**Pull request by kdagnan**
Solves #2158

### CODE REVIEW

**Comment by jelhan** [comment]
Thanks a lot for reporting and fixing this! Do you mind adding a test to ensure that we don't introduce a regression?

**Review by jelhan — APPROVED** [review]
Looks good to me. Thanks a lot for adding test cases as well.

**Review by jelhan — CHANGES_REQUESTED** [review]
Please take care of the linting errors.

**Review by jelhan — CHANGES_REQUESTED** [review]
Linting is still failing.

**Comment by kdagnan** [comment]
Sorry, I was expecting that `npm test` ran linting too. Should *actually* be good now

**Review by jelhan — APPROVED** [review]

**Comment by jelhan** [comment]
Released as [v6.4.1](https://github.com/ember-bootstrap/ember-bootstrap/releases/tag/v6.4.1).

**Pull request merged**
