### PR TITLE
Support ember-element-helper v0.7.0 and v0.8.0

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
Fixes : https://github.com/ember-bootstrap/ember-bootstrap/issues/1949

### CODE REVIEW

**Review by jelhan — CHANGES_REQUESTED** [review]
Thanks a lot for picking this up.

It seems that you missed updating the `yarn.lock` file by running `yarn install` or missed committing the changes to it. CI fails due to it:

> error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.

Could you please have a look?

**Comment by SaumyaBhushan** [comment]
Hi @jelhan ! Updated the yarn.lock file

**Comment by SaumyaBhushan** [comment]
Hi @jelhan ! Please let me know if anything else needed to be changed here .

**Review by jelhan — APPROVED** [review]
Looks good. Need to fix broken CI, which is not related to this PR before merging. Will release together with #1952 as soon as possible.

**Comment by jelhan** [comment]
@SaumyaBhushan CI is fixed. Please merge latest master into your feature branch.

**Pull request merged**
