### PR TITLE
Refactor BsNav to Glimmer component

### PR DESCRIPTION
**Pull request by SanderKnauff**
* Converts BsNav to Glimmer
* Replaces computed properties in BsNav with getters based on the tracked arguments 

This addresses part of #2012 and #2013

### CODE REVIEW

**Review by jelhan — APPROVED** [review]
Looks good to me.

It's not addressing an observer. Observer is used in `<BsNav::Item>`. I updated the tracking issue as it was not precise. But it fixes computed property usage in `<BsNav>`. I will update PR description accordingly.

Failing tests are likely not related. Need to have a closer look into those.

**Comment by jelhan** [comment]
> Failing tests are likely not related. Need to have a closer look into those.

Failing tests are caused by a bug in Fastboot. Fix is already merged: https://github.com/ember-fastboot/ember-cli-fastboot/pull/929 Hopefully releases soon as well.

As soon as the fix is released, CI pipeline should pass on the next run.

**Comment by jelhan** [comment]
Fix was released few seconds ago. Reopened to trigger new CI run.

**Comment by jelhan** [comment]
@SanderKnauff I fear you need to merge in latest master to fix CI.

The tests are failing due to an update of an indirect dependency. That's why only ember try scenarios are failing. The fix is in a direct dependency, which must be upgraded explicitly. The good thing is: RebovateBot took already care of it over night. So pulling in latest master should be all needed.

I'm sorry for the inconvenience.

**Comment by SanderKnauff** [comment]
> Looks good to me.
> 
> It's not addressing an observer. Observer is used in `<BsNav::Item>`. I updated the tracking issue as it was not precise. But it fixes computed property usage in `<BsNav>`. I will update PR description accordingly.
> 
> Failing tests are likely not related. Need to have a closer look into those.

Ah yeah. I confused the Observers and Computer properties.

> @SanderKnauff I fear you need to merge in latest master to fix CI.
> 
> The tests are failing due to an update of an indirect dependency. That's why only ember try scenarios are failing. The fix is in a direct dependency, which must be upgraded explicitly. The good thing is: RebovateBot took already care of it over night. So pulling in latest master should be all needed.
> 
> I'm sorry for the inconvenience.

That's okay, a small rebase is hardly any work :)
It's just good to know that it wasn't the Glimmer migration that broke the update.

**Pull request merged**
